version: '3.8'

services:
  zitate-web:
    container_name: zitate-web
    image: ghcr.io/thst71/zitate-web:1
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "com.zitate.app=web"
      - "com.zitate.version=1.0"
