version: '3.8'

services:
  zitate-web-1:
    container_name: zitate-web
    image: ghcr.io/thst71/zitate-web:1
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  zitate-web-2:
    container_name: zitate-web-2
    image: ghcr.io/thst71/zitate-web:2
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  zitate-web-build:
    container_name: zitate-web-build
    image: ghcr.io/thst71/zitate-web:local
    build:
      context: Zitate.web/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "com.zitate.app=web"
      - "com.zitate.version=SNAPSHOT"
